version: "3"
services:
  csharp:
    container_name: csharp
    image: ishtilkind/csharp:1.0.0
    build: ./c#
  golang:
    container_name: golang
    image: ishtilkind/golang:1.0.0
    build: ./golang
  nodejs:
    container_name: nodejs
    image: ishtilkind/nodejs:1.0.0
    build: ./golang 
  python:
    container_name: python
    image: ishtilkind/python:1.0.0
    build: ./python 
