version: "3"
services:
  csharp:
    container_name: csharp
    image: ishtilkind/csharp:1.0.0
    build: ./c#
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    volumes:
      - ./c#/scr/:/work
    ports:
      - 5000:5000
  golang:
    container_name: golang
    image: ishtilkind/golang:1.0.0
    build: ./golang
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./golang/src/:/work
    ports:
      - 5001:5000
  nodejs:
    container_name: nodejs
    image: ishtilkind/nodejs:1.0.0
    build: ./nodejs
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./nodejs/src/:/work
    ports:
      - 5002:5000
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: python
    image: ishtilkind/python:1.0.0
    build: ./python
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./python/src/:/work
    ports:
      - 5003:5000
